jobs:
  run-pipeline:
    # …
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: functions
        run: npm ci

      - name: Write Service Account Key
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > functions/serviceAccountKey.json

      - name: Run Forecast Pipeline
        working-directory: functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/functions/serviceAccountKey.json
        run: node pipeline.js
