name: Deploy Forecast Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: functions
        run: npm ci

      - name: Authenticate to Firestore
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json

      - name: Run Forecast Pipeline
        working-directory: functions
        run: node pipeline.js
