# .github/workflows/deploy.yml
name: Deploy Forecast Pipeline

on:
  schedule:
    # every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Write Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > functions/serviceAccountKey.json

      - name: Install dependencies
        working-directory: functions
        run: npm ci

      - name: Run Forecast Pipeline
        working-directory: functions
        run: node pipeline.js
